[package]
name = "console-audio-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.101.0"
rodio = "0.17.3"
terminal-input = "0.1.0"

